<?php

namespace Database\Seeders;

use App\Enums\StatutDemandeEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemandeLivraisonSeeder extends Seeder
{
    public $table = 'demande_livraisons';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table($this->table)->insert([
            [
                'ref_operation' =>'Ref1',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21008',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],


            [
                'ref_operation' =>'Ref2',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benji',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21009',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>'2022-05-01',
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],



            [
                'ref_operation' =>'Ref3',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benji',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21001',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>'2022-05-01',
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],



            [
                'ref_operation' =>'Ref4',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21078',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],


            [
                'ref_operation' =>'Ref5',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21608',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>2,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref6',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>10000000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'21308',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

            [
                'ref_operation' =>'Ref13',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'91108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>'2022-02-01',
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>2,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

            [
                'ref_operation' =>'Ref14',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Owendo',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'81108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>'2022-02-01',
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>2,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

            [
                'ref_operation' =>'Ref15',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Owendo',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'71128',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

            [
                'ref_operation' =>'Ref16',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Owendo',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'71119',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref12',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Pk',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'71108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

            [
                'ref_operation' =>'Ref17',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Pk',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'71140',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref7',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Pk',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'61108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref8',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>150000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'51108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref9',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville-Akanda ',
                'nom_beneficiaire'=>'Khalde ouro ariziki wiyao soussa dema',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>10000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'41108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_EFFECTUEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref10',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'31108',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'ref_operation' =>'Ref11',
                'code_agence'=>'AG_000001',
                'nom_client'=>'Benj',
                'tel_client'=>'065998685',
                'adresse_livraison'=>'Libreville',
                'nom_beneficiaire'=>'Khalde',
                'tel_beneficiaire'=>'012263',
                'montant_livraison'=>50000,
                'nombreBillet10000'=>3,
                'nombreBillet5000'=>4,
                'frais_livraison'=>5000,
                'voucher'=>'23100',
                'lien_gps'=>'https://google_maps',
                'date_reception'=>now(),
                'date_livraison'=>now(),
                'statut_demande_id'=> DEMANDE_INITIEE,
                'user_id'=>'1',
                'livreur_id'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);
    }
}
